export const COMMON_ARRAY = [
  { title: "IMEI", endPoint: "imei" },
  { title: "Manufacturer", endPoint: "manufacturer" },
  { title: "Name", endPoint: "machineName" },
  { title: "Client", endPoint: "client" },
  { title: "Machine Model", endPoint: "machineModel" },
  { title: "Brand", endPoint: "brand" },
  { title: "Category", endPoint: "category" },
  { title: "States", endPoint: "states" },
  { title: "Department", endPoint: "department" },
  { title: "Maintenance Interval", endPoint: "maintainanceInterval" },
  { title: "Last Maintenance", endPoint: "lastMaintenance" },
  { title: "Initial Maintenance", endPoint: "initialMaintenance" },
  { title: "Smart Device", endPoint: "smartDevice" },
  { title: "Serial Number", endPoint: "serialNumber" },
  { title: "Equipment Model", endPoint: "equipmentModel" },
  { title: "Speed", endPoint: "speed" },
  { title: "RPM", endPoint: "rpm" },
  { title: "Fuel Level", endPoint: "fuelLevel" },
  { title: "Odometer", endPoint: "odometer" },
  { title: "Hour Meter", endPoint: "hourMeter" },
  { title: "Hydraulic Pressure", endPoint: "hydraulicPressure" },
  { title: "Track", endPoint: "track" },
  { title: "Boom Angle", endPoint: "boomAngle" },
  { title: "Engine Temperature", endPoint: "engineTemperature" },
  { title: "Brake Fluid Level", endPoint: "brakeFluidLevel" },
  { title: "Engine Oil Level", endPoint: "engineOilLevel" },
  { title: "Gear Oil Level", endPoint: "gearOilLevel" },
  { title: "Engine Warning PID", endPoint: "engineWarningPID" },
  { title: "Hydraulic Warning PID", endPoint: "hydraulicWarningPID" },
  { title: "Electronics Warning PID", endPoint: "electronicsWarningPID" },
  { title: "Brake Warning PID", endPoint: "brakeWarningPID" },
  { title: "Transmission Warning PID", endPoint: "transmissionWarningPID" },
  { title: "Latitude", endPoint: "latitude" },
  { title: "Longitude", endPoint: "longitude" },
  { title: "Battery Voltage", endPoint: "batteryVoltage" },
  { title: "Hours of Operation", endPoint: "hoursOfOperation" },
  { title: "DI1", endPoint: "DI1" },
  { title: "DI2", endPoint: "DI2" },
  { title: "DO1", endPoint: "DO1" },
  { title: "DO2", endPoint: "DO2" },
  { title: "AI1", endPoint: "AI1" },
  { title: "AI2", endPoint: "AI2" },
  { title: "User", endPoint: "user" },
  { title: "Maintenance Contract", endPoint: "maintainaceContract" },
];
export const REGISTRATION = [
  { title: "Name", endPoint: "machineName" },
  { title: "Organization", endPoint: "organization" },
  { title: "Serial Number", endPoint: "serialNumber" },
  { title: "Manufacturer", endPoint: "manufacturer" },
  { title: "Model", endPoint: "machineModel" },
  { title: "Category", endPoint: "category" },
  { title: "Smart Device", endPoint: "smartDevice" },
  { title: "IMEI", endPoint: "imei" },
  { title: "Maintenance Contract", endPoint: "maintainaceContract" },
  { title: "State", endPoint: "states" },
  { title: "Department", endPoint: "department" },
  { title: "Initial Maintenance Interval (Hours)", endPoint: "initialMaintenance" },
  { title: "Regular Maintenance Interval (Hours)", endPoint: "maintainanceInterval" },
  { title: "Last Maintenance (Hours)", endPoint: "lastMaintenance" },
];

export const Status = [{ title: "Dynamic Parameters", endPoint: "dynamicParameters" }];

export const Maintenance = [
  { title: "Last Maintenance Hours", endPoint: "lastMaintenanceHours" },
  { title: "Time Made By", endPoint: "timeMadeBy" },
  // Add more maintenance-related parameters as needed
];

export const Failure = [
  { title: "Timestamp", endPoint: "timestamp" },
  { title: "Failure Group", endPoint: "failureGroup" },
  { title: "Suspect Parameter", endPoint: "suspectParameter" },
  { title: "Description", endPoint: "description" },
];
